# Generated by Django 3.2.25 on 2024-06-29 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalexperience',
            name='work_details',
        ),
        migrations.CreateModel(
            name='Experience_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_point', to='portfolioApp.professionalexperience')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_list', to='portfolioApp.worksummary')),
            ],
        ),
    ]
