# Generated by Django 3.2.25 on 2024-06-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_auto_20240629_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
