# Generated by Django 3.2.25 on 2024-06-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_professionalexperience_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=150, null=True)),
                ('institute', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.CharField(blank=True, max_length=255, null=True)),
                ('end_year', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.FloatField(blank=True, null=True)),
                ('quotation', models.TextField()),
            ],
        ),
    ]
