# Generated by Django 3.2.25 on 2024-06-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_auto_20240628_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
