# Generated by Django 3.2.25 on 2024-06-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_auto_20240628_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='portfolioApp.professionalexperience')),
            ],
        ),
    ]
