# Generated by Django 3.2.25 on 2024-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_appdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='App_Images'),
        ),
    ]
