# Generated by Django 3.2.25 on 2024-06-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_worksummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksummary',
            name='company',
        ),
    ]
