# Generated by Django 3.2.25 on 2024-06-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_remove_worksummary_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='work_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_points', to='portfolioApp.worksummary'),
            preserve_default=False,
        ),
    ]
