# Generated by Django 3.2.25 on 2024-06-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_appdetails_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.FileField(blank=True, null=True, upload_to='App_Images')),
            ],
        ),
        migrations.RemoveField(
            model_name='appdetails',
            name='images',
        ),
    ]
