# Generated by Django 3.2.25 on 2024-06-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_auto_20240630_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_details', to='portfolioApp.appdetails')),
                ('app_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_list', to='portfolioApp.appimages')),
            ],
        ),
    ]
