# Generated by Django 3.2.25 on 2024-06-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_remove_app_image_app_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appimages',
            name='images',
        ),
        migrations.AddField(
            model_name='app_image',
            name='app_img',
            field=models.ImageField(blank=True, null=True, upload_to='App_Images'),
        ),
    ]
