# Generated by Django 3.2.25 on 2024-06-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0011_auto_20240630_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='AppDetails_Images'),
        ),
    ]
